stages: [compilation, package, deploy]

job_compilation:
    stage: compilation
    image: maven:eclipse-temurin-21
    before_script:
        - mvn clean package
    script: 
        - echo "compilation with maven"
    artifacts:
        paths:
            - boardgames-build

job_package:
    stage: package
    script: 
        - echo "Push image to docker hub"

job_deploy:
    stage: deploy
    script:
        - echo "Deploying application"