stages: [compilation, package, deploy]

job_compilation:
    stage: compilation
    image: maven:3.9.6-eclipse-temurin-21
    before_script:
        - echo "{$M2_SETTINGS}"
        - touch ~/.m2/settings.xml
        - echo "{$M2_SETTINGS}" >> ~/.m2/settings.xml
        - cd square_games
        - mvn clean package
    script: 
        - echo "compilation with maven"
    artifacts:
        paths:
            - boardgames-build

job_package:
    stage: package
    script: 
        - echo "Push image to docker hub"

job_deploy:
    stage: deploy
    script:
        - echo "Deploying application"