stages: [compilation, package, deploy]

job_compilation:
    stage: compilation
    image: maven:3.9.6-eclipse-temurin-21
    before_script:
        - touch ~/.m2/settings.xml
        - echo $M2_SETTINGS >> ~/.m2/settings.xml
        - cd square_games
        - mvn clean package -DskipTests
    script: 
        - echo "compilation with maven"
        - cd ./target
        - ls -la
    artifacts:
        paths:
            - ./square_games/target

job_docker_image:
    stage: package
    script:
        - touch Dockerfile
        - echo "something" >> ./Dockerfile
        - cat Dockerfile
        - ls -la
        - pwd
    artifacts:
        paths:
            - Dockerfile

job_package:
    stage: package
    script: 
        - echo "Push image to docker hub"
        - pwd
        - ls -la
        - cat Dockerfile
        - echo ./square_games/target/*

job_deploy:
    stage: deploy
    script:
        - echo "Deploying application"